export const LangStrings = {
  "en-US": {
    search: "Search...",
    signin: "Singn In",
    popular: "Popular",
    topRated: "Top Rated",
    nowPlaying: "Now Playing",
    upcoming: "Upcoming",
    footer: "Created by",
    author: "Rafael Viana",
  },
  "pt-BR": {
    search: "Buscar...",
    signin: "Iniciar Sessão",
    popular: "Popular",
    topRated: "Melhores Avaliações",
    nowPlaying: "Agora no Cinema",
    upcoming: "A ser lançado",
    footer: "Criado por",
    author: "Rafael Viana",
  },
  "ja-JP": {
    search: "検索...",
    signin: "ログイン",
    popular: "一番人気",
    topRated: "ベスト　評価",
    nowPlaying: "再生中",
    upcoming: "今後の映画",
    footer: "開発者：　",
    author: "ヴィアナ　ラファエル",
  },
};
